### ISSUE TITLE
Replace the jqplot with Chart.js.

### ISSUE THREAD

**Issue by WakeupTsai** [fabaff/mqtt-panel#5]
Hi, I found that the performance of jqplot is really bad. Browser will become very laggy after a few minutes (even though I constrain the number of value on the plot).

So I wondering if I can pull a request  that replace the jqplot with Chart.js:blush:

**Comment by fabaff** [comment]
I actually don't really care what is used to create the graph. I guess that jqplot was the first library which I found.
