### ISSUE TITLE
No colors on the page

### ISSUE THREAD

**Issue by sponz** [fabaff/mqtt-panel#8]
I have clone your git and launched the test, but I don't see the nice colors as on your demo screenshot. 

![image](https://user-images.githubusercontent.com/1790564/82419936-596c1100-9a7f-11ea-9b33-8d7181fe2931.png)

Is there anything missing? 

Thanks

**Comment by fabaff** [comment]
Bootstrap 4 removed the used CSS class.

Was fixed with https://github.com/fabaff/mqtt-panel/commit/c36f85111ac794b40d09c10c02c2aa6b5315dc6e
